### ISSUE TITLE
Wizard jumps back to beginning randomly, losing entered data and without error

### ISSUE THREAD

**Issue by fulv** [collective/collective.megaphone#6]
I have not been able to isolate a way to consistently reproduce this bug.

Occasionally, when I start creating a new megaphone action, I get partway through the wizard steps.  Then, before I can get to the last page, I click the "Continue" button and am taken back to the start.  Everything entered thus far is lost.  No error is shown the user, nor is there any trace of what happened in the log.  There is no particular wizard step that is problematic, it could be the second, third, or any other.

Any idea what I could do to get more information in the logs, or what to try to figure out how to reproduce it consistently would be welcome.

Thanks

**Comment by davisagli** [comment]
The setup wizard (which uses collective.z3cform.wizard) keeps track of its position in the Zope session. I think one of two things is happening:
a. The user's session is lost (such as if Zope is restarted, or you are using multiple backend instances without using session affinity in your load balancer or sharing the session between instances)
b. There is code which explicitly resets the wizard session if it concludes that the user came from a page that is not part of the wizard. You can debug that here: https://github.com/collective/collective.z3cform.wizard/blob/master/collective/z3cform/wizard/wizard.py#L172

**Comment by fulv** [comment]
Thanks David!  I installed and configured BeakerSessionDataManager and that seemed to do the trick.
You might have already told me what the problem was, but I forgot to make a note of it.

**Comment by davisagli** [comment]
That sounds like problem a above, then.
